# TensorFlow
- Open-source library for graph-based nnumerical compuation
- Low and high level APIs
    - Addition, multiplication, differentiation
    - Machine learning models

In [1]:
# Defining tensors in TensorFlow
import tensorflow as tf

# 0D Tensor
d0 = tf.ones([1,])
print(d0)

# 1D Tensor
d1 = tf.ones([2,])
print(d1)

# 2D Tensor
d2 = tf.ones([2,2])
print(d2)

# 3D Tensor
d3 = tf.ones([2,2,2])
print(d3)

2023-05-20 08:31:51.325865: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-20 08:31:51.325890: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


tf.Tensor([1.], shape=(1,), dtype=float32)
tf.Tensor([1. 1.], shape=(2,), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


2023-05-20 08:31:52.844365: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-05-20 08:31:52.844389: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-05-20 08:31:52.844407: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (6fcbb293-76a9-4cfb-afc7-b983bd4a1dcd): /proc/driver/nvidia/version does not exist
2023-05-20 08:31:52.844662: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Using conveinience functions to define constants

![image](image.png)


- **A constant is the simplest category of tensor**
    - Not trainable
    - Can have any dimension

In [2]:
# Defining constants in TensorFlow
from tensorflow import constant

# Define a 2x3 constant
a = constant(3, shape=[2,3])
print(a)

# Define a 2x2 constant
b = constant([1,2,3,4], shape=[2,2])
print(b)

tf.Tensor(
[[3 3 3]
 [3 3 3]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Defining and initializing variables
- Unlike a constant, a variable's value can be modified. This will be useful when we want to train a model by updating its parameters.

In [3]:
import tensorflow as tf

# Define a variable
a0 = tf.Variable([1,2,3,4,5,6], dtype=tf.float32)
a1 = tf.Variable([1,2,3,4,5,6], dtype=tf.int16)

a0,a1

(<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(6,) dtype=int16, numpy=array([1, 2, 3, 4, 5, 6], dtype=int16)>)

In [4]:
# Define a constant
b = tf.constant(2, tf.float32)
print(b)

tf.Tensor(2.0, shape=(), dtype=float32)


In [5]:
# Compute their product
c0 = tf.multiply(a0, b)
print(c0)

c1 = a0*b
print(c1)

tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)
tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)


# Basic operations

## Applying the addition operator

In [6]:
# Import constant and add from tensorflow
from tensorflow import constant, add

# Define 0-dimensional tensors
A0 = constant([1])
B0 = constant([2])

# Define 1-dimensional tensors
A1 = constant([1,2])
B1 = constant([3,4])

# Define 2-dimensional tensors
A2 = constant([[1,2],[3,4]])
B2 = constant([[5,6],[7,8]])

In [7]:
# Perform tensor addition with add()
C0 = add(A0,B0)
C1 = add(A1,B1)
C2 = add(A2,B2)

print(C0)
print(C1)
print(C2)

tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


- The `add()` operation performs **element-wise addition** with two tensors.
- Element-wise addition requires both tensors to have the same shape

## Perform multiplication in TensorFlow
- **Element-wise multiplication** performed using `multiply()` operation
    - The tensors multiplied must have the same shape
- **Matrix multiplication** performed with `matmul()` operator
    - The `matmul(A,B)` operation multiplies A by B
    - Number of columns of A must equal the number of rows of B

In [8]:
# Import operations from tensorflow
from tensorflow import ones, matmul, multiply

# Define tensors
A0 = ones([1])
A31 = ones([3,1])
A34 = ones([3,4])
A43 = ones([4,3])

In [9]:
# Valid operations -- multiplication
print(multiply(A0, A0))
print(multiply(A31, A31))
print(multiply(A34, A34))

tf.Tensor([1.], shape=(1,), dtype=float32)
tf.Tensor(
[[1.]
 [1.]
 [1.]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [10]:
# Valid operation -- matrix multiplication
print(matmul(A34,A43))

tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]], shape=(3, 3), dtype=float32)


## Summing over tensor dimensions
- The `reduce_sum()` operator sums over the dimensions of a tensor
    - `reduce_sum(A)` sums over all dimensions of A
    - `reduce_sum(A,i)` sums over dimension i 

In [11]:
# Import operations from tensorflow
from tensorflow import ones, reduce_sum

# Define a 2x3x4 tensor of ones
A = ones([2,3,4])
print(A)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


In [12]:
# Sum over all dimensions
print(reduce_sum(A))

tf.Tensor(24.0, shape=(), dtype=float32)


In [13]:
# Sum over dimensions 0,1, and 2
B0 = reduce_sum(A,0) #<- along z-axis
B1 = reduce_sum(A,1) #<- along y-axis
B2 = reduce_sum(A,2) #<- along x-axis

print(B0)
print(B1)
print(B2)

tf.Tensor(
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)


# Advanced operations
- `gradient()` - computes the slope of a function at a point
- `reshape()` - Reshapes a tensor (eg 10x10 to 100x1)
- `random()` - Populates tensor with entries drawn from a probability distribution

## Finding the optimum
- In many problems, we will want to find the optimum of a function
    - **Minimum:** Lowest value of a loss function
    - **Maximum:** Highest value of objective function
- We can do this using the `gradient()` operation
    - **Optimum**: Find a point where gradient=0
    #Since, weight is updated with respect to the gradient value i.e wt = wt - grad
    - **Mimimum**: Change in gradient > 0, weight is decreased (min)
    - **Maximum**: Change in gradient < 0, weight is increased (max)

In [14]:
# Import tensorflow under the alias tf
import tensorflow as tf

# Define x
x = tf.Variable(-1.0)

In [16]:
# Define y within instance of GradientTape
with tf.GradientTape() as tape:
    tape.watch(x) #<-- we apply the watch method to an instance of gradient tape and then pass the variable x. This will allow us to compute the rate of change of y with respect to x. 
    y = tf.multiply(x,x)

In [17]:
# Evaluate the gradient of y at x = -1
g = tape.gradient(y,x)
print(g.numpy())

-2.0


We find that the slope is -2 at x equals -1, which means that y is initially decreasing in x.

![image-2](image-2.png)
